# Cleaning and formatting cytokines data

In [13]:
import re
import polars as pl

In [14]:
# Load data
df = pl.read_csv(
    "../data/CV_plasma_Combined_cleaned_20260731.csv",
    infer_schema_length=None
)

In [15]:
# Variables mapping dict
cat_vars_mapping = {
    "Sex": {1: "male", 2: "female"},
    "Race": {
        1: "white_nonhispanic",
        2: "white_hispanic",
        3: "black_nonhispanic",
        4: "black_hispanic",
        5: "asian",
        6: "others",
    },
    "Tobaccouse": {1: "never", 2: "former", 3: "current"},
    "Alcoholuse": {1: "never", 2: "former", 3: "current"},
    "pathologicstage": {
        1: "stage_I",
        2: "stage_II",
        3: "stage_III",
        4: "stage_IVA",
        5: "stage_IVB"
    },
    "LVI": {0: "no", 1: "yes"},
    "PNI": {0: "no", 1: "yes"},
    "survival_status": {0: "alive", 1: "death"},
    "survival_2yrs": {0: "alive", 1: "death"}
}

In [16]:
# Remapping categorical variables to their corresponding values
df = df.with_columns(
    [pl.col(var).replace_strict(mapping).alias(var) for var, mapping in cat_vars_mapping.items()]
)

In [17]:
df["survival_2yrs"].value_counts()

shape: (2, 2)
┌───────────────┬───────┐
│ survival_2yrs ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ death         ┆ 61    │
│ alive         ┆ 151   │
└───────────────┴───────┘

In [18]:
df.head()

shape: (5, 43)
┌──────────────┬───────────┬────────┬────────┬───┬──────────────┬──────────────┬─────────────┬─────┐
│ sample_names ┆ sample_id ┆ Cohort ┆ EGF    ┆ … ┆ survival_sta ┆ sx_to_lastfu ┆ survival_2y ┆ ss  │
│ ---          ┆ ---       ┆ ---    ┆ ---    ┆   ┆ tus          ┆ ---          ┆ rs          ┆ --- │
│ str          ┆ str       ┆ str    ┆ f64    ┆   ┆ ---          ┆ i64          ┆ ---         ┆ i64 │
│              ┆           ┆        ┆        ┆   ┆ str          ┆              ┆ str         ┆     │
╞══════════════╪═══════════╪════════╪════════╪═══╪══════════════╪══════════════╪═════════════╪═════╡
│ FF301C       ┆ FF301C    ┆ LLU    ┆ 29.45  ┆ … ┆ alive        ┆ 1839         ┆ alive       ┆ 1   │
│ FF302C       ┆ FF302C    ┆ LLU    ┆ 71.5   ┆ … ┆ alive        ┆ 1721         ┆ alive       ┆ 4   │
│ FF303C       ┆ FF303C    ┆ LLU    ┆ 54.54  ┆ … ┆ death        ┆ 48           ┆ death       ┆ 4   │
│ FF304C       ┆ FF304C    ┆ LLU    ┆ 132.67 ┆ … ┆ death        ┆ 131          ┆ death       ┆ 3   │
│ FF305C       ┆ FF305C    ┆ LLU    ┆ 28.01  ┆ … ┆ alive        ┆ 1679         ┆ alive       ┆ 1   │
└──────────────┴───────────┴────────┴────────┴───┴──────────────┴──────────────┴─────────────┴─────┘

In [19]:
# df.schema
df.null_count()

shape: (1, 43)
┌──────────────┬───────────┬────────┬─────┬───┬───────────────┬──────────────┬───────────────┬─────┐
│ sample_names ┆ sample_id ┆ Cohort ┆ EGF ┆ … ┆ survival_stat ┆ sx_to_lastfu ┆ survival_2yrs ┆ ss  │
│ ---          ┆ ---       ┆ ---    ┆ --- ┆   ┆ us            ┆ ---          ┆ ---           ┆ --- │
│ u32          ┆ u32       ┆ u32    ┆ u32 ┆   ┆ ---           ┆ u32          ┆ u32           ┆ u32 │
│              ┆           ┆        ┆     ┆   ┆ u32           ┆              ┆               ┆     │
╞══════════════╪═══════════╪════════╪═════╪═══╪═══════════════╪══════════════╪═══════════════╪═════╡
│ 0            ┆ 0         ┆ 0      ┆ 0   ┆ … ┆ 0             ┆ 0            ┆ 0             ┆ 0   │
└──────────────┴───────────┴────────┴─────┴───┴───────────────┴──────────────┴───────────────┴─────┘

In [20]:
df.glimpse()

Rows: 212
Columns: 43
$ sample_names                  <str> 'FF301C', 'FF302C', 'FF303C', 'FF304C', 'FF305C', 'FF306C', 'FF307C', 'FF308C', 'FF310C', 'FF312C'
$ sample_id                     <str> 'FF301C', 'FF302C', 'FF303C', 'FF304C', 'FF305C', 'FF306C', 'FF307C', 'FF308C', 'FF310C', 'FF312C'
$ Cohort                        <str> 'LLU', 'LLU', 'LLU', 'LLU', 'LLU', 'LLU', 'LLU', 'LLU', 'LLU', 'LLU'
$ EGF                           <f64> 29.45, 71.5, 54.54, 132.67, 28.01, 66.25, 76.93, 16.56, 36.06, 65.71
$ IFNalpha2                     <f64> 25.24, 9.93, 18.38, 27.47, 13.63, 19.54, 7.36, 0.04, 18.38, 0.04
$ IFNgamma                      <f64> 90.0, 46.35, 54.01, 81.82, 66.2, 54.01, 21.11, 37.59, 31.81, 34.84
$ IL1alpha                      <f64> 6.4, 0.0, 46.49, 6.89, 5.44, 2.12, 1.21, 0.0, 12.32, 0.0
$ IL1beta                       <f64> 3.95, 0.0, 18.9, 3.95, 0.92, 1.38, 0.0, 0.0, 4.57, 0.0
$ IL4                           <f64> 4.21, 2.33, 1.37, 4.56, 3.04, 1.97, 1.01, 0.57, 1.37, 0.51
$ IL6                           <f64> 3.54, 3.42, 4.15, 9.69, 2.42, 17.13, 1.51, 1.51, 3.2, 2.19
$ IL8                           <f64> 4.14, 4.53, 3.57, 7.29, 5.44, 3.91, 1.48, 1.11, 3.21, 6.1
$ IL10                          <f64> 3.92, 75.2, 98.33, 20.63, 10.63, 18.54, 3.55, 0.98, 178.28, 10.81
$ MIP1alpha                     <f64> 25.93, 2.9, 25.05, 20.32, 17.14, 7.53, 0.0, 0.0, 14.8, 7.53
$ TGFalpha                      <f64> 3.32, 1.52, 2.99, 4.31, 3.98, 2.54, 0.2, 0.06, 4.09, 0.2
$ TNFalpha                      <f64> 18.74, 25.54, 22.39, 28.18, 39.61, 12.95, 9.54, 9.54, 14.58, 19.9
$ TNFbeta                       <f64> 10.46, 3.74, 4.83, 9.32, 5.94, 2.5, 1.0, 13.09, 4.99, 2.5
$ HBEGF                         <f64> 83.27, 75.2, 51.96, 85.47, 71.54, 51.6, 57.37, 23.14, 37.99, 45.49
$ VEGFC                         <f64> 381.47, 923.75, 490.19, 1148.22, 1113.45, 879.23, 722.23, 322.45, 385.38, 294.67
$ VEGFD                         <f64> 263.05, 237.53, 130.47, 34.22, 142.55, 80.33, 169.8, 142.55, 272.58, 292.65
$ Ages                          <i64> 67, 68, 78, 49, 65, 31, 66, 58, 72, 88
$ Sex                           <str> 'female', 'male', 'male', 'male', 'female', 'male', 'male', 'female', 'male', 'male'
$ Race                          <str> 'white_nonhispanic', 'white_nonhispanic', 'white_nonhispanic', 'white_nonhispanic', 'white_nonhispanic', 'white_nonhispanic', 'white_nonhispanic', 'asian', 'white_nonhispanic', 'white_nonhispanic'
$ Tobaccouse                    <str> 'never', 'former', 'never', 'current', 'former', 'former', 'former', 'never', 'former', 'former'
$ Packyears                     <f64> 0.0, 52.5, 0.0, 72.0, 42.0, 5.0, 36.0, 0.0, 69.0, 52.0
$ Alcoholuse                    <str> 'never', 'former', 'current', 'current', 'never', 'never', 'current', 'never', 'current', 'current'
$ AverageUCSF                   <f64> 1.5, 68.75, 67.5, 95.0, 37.0, 58.75, 10.75, 46.63, 8.0, 38.75
$ Spontaneouspain135            <f64> 0.33, 36.67, 63.33, 86.67, 11.0, 50.0, 0.0, 39.67, 3.0, 10.0
$ Functionalpain246             <f64> 0.33, 80.0, 63.33, 100.0, 33.67, 66.67, 20.67, 43.67, 8.33, 50.0
$ BPIPhysicalinterferences      <f64> 0.0, 21.0, 9.0, 0.0, 2.0, 17.0, 0.0, 15.0, 5.0, 4.0
$ BPIPsychologicalinterferences <i64> 0, 32, 4, 0, 10, 36, 0, 23, 34, 11
$ BPI_intensity                 <f64> 0.0, 23.0, 22.0, 29.0, 18.0, 26.0, 5.0, 19.0, 21.0, 8.0
$ Functionalscores              <f64> 83.33, 54.33, 39.67, 0.0, 82.67, 8.0, 98.67, 74.0, 78.33, 75.0
$ Symptomscore                  <f64> 19.44, 59.03, 31.25, 68.75, 27.08, 75.0, 6.25, 11.11, 38.19, 18.75
$ GlobalhealthstatusQL2         <f64> 75.0, 16.67, 50.0, 0.0, 75.0, 58.33, 91.67, 50.0, 0.0, 33.33
$ QLQ30score                    <f64> 81.62, 46.11, 57.56, 19.23, 76.67, 18.46, 95.64, 83.16, 68.16, 78.85
$ HN35                          <f64> 30.56, 47.78, 45.68, 94.44, 17.44, 71.76, 10.8, 27.44, 49.97, 27.31
$ pathologicstage               <str> 'stage_I', 'stage_IVA', 'stage_IVA', 'stage_IVA', 'stage_II', 'stage_IVB', 'stage_III', 'stage_IVA', 'stage_III', 'stage_IVB'
$ LVI                           <str> 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no'
$ PNI                           <str> 'no', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes'
$ survival_status               <str> 'alive', 'alive', 'death', 'death', 'alive', 'death', 'death', 'alive', 'alive', 'death'
$ sx_to_lastfu                  <i64> 1839, 1721, 48, 131, 1679, 318, 278, 1765, 1758, 997
$ survival_2yrs                 <str> 'alive', 'alive', 'death', 'death', 'alive', 'death', 'death', 'alive', 'alive', 'alive'
$ ss                            <i64> 1, 4, 4, 3, 1, 4, 4, 4, 4, 4

In [21]:
df.describe()

shape: (9, 44)
┌────────────┬────────────┬───────────┬────────┬───┬────────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ sample_nam ┆ sample_id ┆ Cohort ┆ … ┆ survival_s ┆ sx_to_las ┆ survival_ ┆ ss       │
│ ---        ┆ es         ┆ ---       ┆ ---    ┆   ┆ tatus      ┆ tfu       ┆ 2yrs      ┆ ---      │
│ str        ┆ ---        ┆ str       ┆ str    ┆   ┆ ---        ┆ ---       ┆ ---       ┆ f64      │
│            ┆ str        ┆           ┆        ┆   ┆ str        ┆ f64       ┆ str       ┆          │
╞════════════╪════════════╪═══════════╪════════╪═══╪════════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 212        ┆ 212       ┆ 212    ┆ … ┆ 212        ┆ 212.0     ┆ 212       ┆ 212.0    │
│ null_count ┆ 0          ┆ 0         ┆ 0      ┆ … ┆ 0          ┆ 0.0       ┆ 0         ┆ 0.0      │
│ mean       ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 908.30188 ┆ null      ┆ 2.79717  │
│            ┆            ┆           ┆        ┆   ┆            ┆ 7         ┆           ┆          │
│ std        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 554.44003 ┆ null      ┆ 1.366974 │
│ min        ┆ 10         ┆ FF301C    ┆ LLU    ┆ … ┆ alive      ┆ 15.0      ┆ alive     ┆ 0.0      │
│ 25%        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 414.0     ┆ null      ┆ 2.0      │
│ 50%        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 846.0     ┆ null      ┆ 3.0      │
│ 75%        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 1470.0    ┆ null      ┆ 4.0      │
│ max        ┆ P-039      ┆ S0080     ┆ UAB    ┆ … ┆ death      ┆ 1917.0    ┆ death     ┆ 6.0      │
└────────────┴────────────┴───────────┴────────┴───┴────────────┴───────────┴───────────┴──────────┘

In [22]:
# Clean columnn names
df = df.rename(
    {
        col: re.sub(r"\s+", "_", re.sub(r"[^\w\s]", "", col.strip().lower()))
        for col in df.columns
    }
)

In [23]:
# Recheck the data after cleaning
df.describe()

shape: (9, 44)
┌────────────┬────────────┬───────────┬────────┬───┬────────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ sample_nam ┆ sample_id ┆ cohort ┆ … ┆ survival_s ┆ sx_to_las ┆ survival_ ┆ ss       │
│ ---        ┆ es         ┆ ---       ┆ ---    ┆   ┆ tatus      ┆ tfu       ┆ 2yrs      ┆ ---      │
│ str        ┆ ---        ┆ str       ┆ str    ┆   ┆ ---        ┆ ---       ┆ ---       ┆ f64      │
│            ┆ str        ┆           ┆        ┆   ┆ str        ┆ f64       ┆ str       ┆          │
╞════════════╪════════════╪═══════════╪════════╪═══╪════════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 212        ┆ 212       ┆ 212    ┆ … ┆ 212        ┆ 212.0     ┆ 212       ┆ 212.0    │
│ null_count ┆ 0          ┆ 0         ┆ 0      ┆ … ┆ 0          ┆ 0.0       ┆ 0         ┆ 0.0      │
│ mean       ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 908.30188 ┆ null      ┆ 2.79717  │
│            ┆            ┆           ┆        ┆   ┆            ┆ 7         ┆           ┆          │
│ std        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 554.44003 ┆ null      ┆ 1.366974 │
│ min        ┆ 10         ┆ FF301C    ┆ LLU    ┆ … ┆ alive      ┆ 15.0      ┆ alive     ┆ 0.0      │
│ 25%        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 414.0     ┆ null      ┆ 2.0      │
│ 50%        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 846.0     ┆ null      ┆ 3.0      │
│ 75%        ┆ null       ┆ null      ┆ null   ┆ … ┆ null       ┆ 1470.0    ┆ null      ┆ 4.0      │
│ max        ┆ P-039      ┆ S0080     ┆ UAB    ┆ … ┆ death      ┆ 1917.0    ┆ death     ┆ 6.0      │
└────────────┴────────────┴───────────┴────────┴───┴────────────┴───────────┴───────────┴──────────┘

In [24]:
# Writing cleaned and formatted cytokines data
df.write_csv(
    "../data/CV_plasma_Combined_formatted_20260731.csv",
    separator=",",
    include_header=True,
    null_value="",
    quote_style="necessary"
)